# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            dougbtv
tagline:          'slangin code in burlington, vt'
description:      'Linux. NFV. Containers. Asterisk. Full-stack JavaScript. Web apps. Î¼C&rsquo;s. <a href="https://twitter.com/dougbtv" target="_blank">@dougbtv</a>.'
url:              http://dougbtv.com/
baseurl:          /

author:
  name:           'dougbtv'
  url:            https://twitter.com/dougbtv

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/dougbtv/dougbtv.github.io

accounts:
  github:         https://github.com/dougbtv
  stackexchange:  http://stackoverflow.com/users/1681171/dougbtv
